"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Main Header
    home: "Inicio",
    ourTeachers: "Nuestros profesores",
    pricing: "Precios",
    hiring: "Contratación",
    blog: "Blog",
    contact: "Contacto",
    register: "Registrarse",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    dashboard: "Panel",
    joinNow: "Comienza tu aventura",
    watchTrailer: "Ver demo",
    heroTitle: "St. George English",
    heroSubtitle: "Aprende inglés explorando el universo",
    heroDescription: "Embárcate en un viaje lingüístico a través de la Galaxia Inglesa. Sin libros de texto, sin conferencias aburridas, solo pura exploración interestelar.",
    
    // Dashboard Header
    teacher: "Profesor",
    sessions: "Sesiones",
    bookings: "Reservas",
    availabilityMenu: "Disponibilidad",
    earnings: "Ganancias",
    forum: "Foro",
    moderation: "Moderación",
    yourClasses: "Tus clases",
    bookClasses: "Reservar clases",
    bookByTeacher: "Reservar por profesor",
    bookByDate: "Reservar por fecha",
    credits: "Créditos",
    buyCredits: "Comprar créditos",
    shareCredits: "Compartir créditos",
    profile: "Perfil",
    
    // Notifications
    notifications: "Notificaciones",
    viewAll: "Ver todo",
    noNotifications: "No hay notificaciones aún.",
    markRead: "Marcar leído",
    
    // Home Page
    methodologyTitle: "Metodología de St. George",
    methodologyDesc: "Nuestro exclusivo Camino a la Fluidez ayuda a los estudiantes a aprender inglés de forma natural, paso a paso.",
    stepListen: "Escuchar",
    stepListenDesc: "Comprende inglés natural y de la vida real a través de práctica de escucha inmersiva.",
    stepSpeak: "Hablar",
    stepSpeakDesc: "Expresa ideas claramente y construye confianza en conversaciones cotidianas.",
    stepWrite: "Escribir",
    stepWriteDesc: "Comunícate efectivamente por escrito con ejercicios guiados.",
    stepRead: "Leer",
    stepReadDesc: "Construye vocabulario e internaliza gramática a través de lectura atractiva.",
    whyStGeorge: "¿Por qué St. George?",
    whyStGeorgeDesc: "Combinamos metodología probada con diversión temática espacial para que cada estudiante se mantenga motivado y progrese realmente.",
    personalizedPaths: "Rutas de aprendizaje personalizadas",
    qualifiedTeachers: "Profesores nativos calificados",
    missionBasedLessons: "Lecciones basadas en misiones",
    exploreLessons: "Explorar lecciones",
    seriouslyFunTitle: "Nuestras lecciones son seriamente divertidas",
    seriouslyFunDesc1: "Nuestras misiones de inglés están diseñadas para mantener la atención con lecciones cortas, práctica simple y cuestionarios rápidos.",
    seriouslyFunDesc2: "Aprende en cualquier lugar, en cualquier momento, y construye vocabulario y confianza paso a paso.",
    seriouslyFunDesc3: "Estarás aprendiendo tanto que ni siquiera notarás que estás estudiando.",
    methodologyFullTitle: "Metodología de St. George",
    methodologyFullDesc1: "En St. George, usamos nuestra metodología exclusiva llamada",
    pathToFluency: "Camino a la Fluidez",
    methodologyFullDesc2: "diseñada para ayudar a los estudiantes a aprender inglés de forma natural, estructurada y atractiva, como adquirir su primer idioma.",
    methodologyFullDesc3: "Lo que realmente hace única nuestra metodología es que diseñamos nuestros propios materiales, adaptados a la edad y nivel de conocimiento de cada estudiante.",
    methodologyFullDesc4: "Este enfoque personalizado y práctico asegura que cada clase no solo sea efectiva, sino también",
    methodologyFullDesc5: "divertida, motivadora y significativa",
    methodologyFullDesc6: "para que los estudiantes disfruten el proceso mientras se vuelven fluidos en inglés.",
    selectTimeTitle: "Selecciona tu hora de estudio, día y misión",
    selectTimeDesc1: "No necesitas viajar: aprende desde casa con práctica corta y enfocada.",
    selectTimeDesc2: "Elige una lección, sigue los ejemplos y luego ponte a prueba.",
    startLearning: "¡Comienza a aprender!",
    customMaterialsTitle: "Materiales personalizados para cada estudiante",
    customMaterialsDesc: "Diseñamos nuestros propios recursos, adaptados a la edad y nivel de conocimiento de cada estudiante.",
    illustratedFlashcards: "Tarjetas ilustradas",
    themedGames: "Juegos temáticos",
    interactiveWorksheets: "Hojas de trabajo interactivas",
    educationalBoardGames: "Juegos de mesa educativos",
    gamifiedActivities: "Actividades gamificadas",
    startFirstMission: "Comienza tu primera misión",
    bridgingGapTitle: "Cerrando la brecha",
    bridgingGapDesc: "Misiones guiadas que hacen que aprender se sienta simple y divertido.",
    kidTestedTitle: "Probado por niños",
    kidTestedDesc: "Lecciones cortas diseñadas para mantener la atención y construir confianza.",
    onlineNewHomeTitle: "En línea es el nuevo hogar",
    onlineNewHomeDesc: "Aprende en cualquier lugar y verifica tu progreso con cuestionarios rápidos.",
    moreAboutMissions: "Más sobre nuestras misiones de inglés",
    lookNoFurtherTitle: "No busques más\n¡Comienza hoy!",
    lookNoFurtherDesc1: "Comienza con lecciones cortas, aprende vocabulario útil y termina con cuestionarios rápidos. Perfecto para práctica diaria.",
    lookNoFurtherDesc2: "Aprende en cualquier lugar, en cualquier momento, y construye confianza paso a paso.",
    joinNowCta: "¡Únete ahora!",
    
    // Testimonials
    whatLearnersSay: "Lo que dicen nuestros estudiantes",
    leaveReviewGoogle: "Déjanos una reseña en Google",
    readMore: "Leer más",
    of: "de",
    
    // Footer
    keepLearning: "Sigue aprendiendo",
    smallStepsEveryDay: "Pequeños pasos, cada día",
    quickLinks: "Enlaces rápidos",
    lessons: "Lecciones",
    quizzes: "Cuestionarios",
    vocabulary: "Vocabulario",
    aboutUs: "Sobre nosotros",
    aboutStGeorge: "Sobre St. George",
    ourMethodology: "Nuestra metodología",
    contactUs: "Contáctanos",
    communityForum: "Foro comunitario",
    faq: "Preguntas frecuentes",
    getStarted: "Comenzar",
    getStartedDesc: "Comienza tu viaje de aprendizaje de inglés hoy con nuestras lecciones interactivas y profesores expertos.",
    bookFreeTrial: "Reservar prueba gratis",
    copyright: "Derechos de autor",
    allRightsReserved: "Todos los derechos reservados",
    termsConditions: "Términos y condiciones",
    legalAdvisory: "Aviso legal",
    privacyPolicy: "Política de privacidad",
    
    // Our Teachers Page
    ourTeachersTitle: "Nuestros profesores",
    ourTeachersDesc: "Aprende inglés en un contexto natural y práctico estudiando situaciones de la vida real que te permitirán destacar en el idioma. Nuestros materiales didácticos están diseñados para hacer que nuestras clases no solo sean informativas sino también increíblemente entretenidas. Además, adaptamos nuestro plan de estudios a la edad de cada estudiante, asegurando que el aprendizaje sea natural y fascinante. ¡Únete ahora y experimenta el programa de capacitación en inglés más atractivo y efectivo disponible!",
    bookFreeTrialNow: "¡Reserva una clase de prueba gratis ahora!",
    viewPricing: "Ver precios",
    teacherSelectionTitle: "Nuestro proceso de selección de profesores",
    teacherSelectionDesc: "Reconocemos que nuestro método es único y especial, y nuestras expectativas para las clases son muy altas.",
    selectionProcess: "Proceso de selección",
    selectionProcessDesc: "Seleccionamos profesores por claridad, paciencia y comunicación amigable con los niños.",
    energyCharisma: "Energía y carisma",
    energyCharismaDesc: "Las lecciones son animadas y atractivas para mantener la atención de principio a fin.",
    highEnergy: "Alta energía",
    highEnergyDesc: "La práctica interactiva hace que los estudiantes participen, no solo observen.",
    childAttention: "Atención del niño",
    childAttentionDesc: "Misiones cortas y pasos claros ayudan a construir confianza rápidamente.",
    qualityMonitoringDesc: "No nos detenemos ahí. Nuestro Coordinador de Profesores y Jefe de Estudios monitorean las clases para garantizar la calidad, sugieren mejoras y capacitan a los profesores para un progreso continuo. Mantenemos altos estándares y mejoramos junto con nuestros profesores.",
    meetTeachersTitle: "Conoce a algunos de nuestros profesores de inglés",
    experiencedEducators: "Educadores experimentados de todo el mundo",
    englishTeacher: "Profesor de inglés",
    ourSecretary: "Nuestra secretaria",
    socialMediaManager: "Gerente de redes sociales",
    contentDeveloper: "Desarrollador de contenido educativo",
    joinClubCta: "¡¡Es hora del inglés!! ¡¡Únete a nuestro club!!",
    
    // Pricing Page
    admitOne: "Admite uno",
    admitFive: "Admite cinco",
    admitTen: "Admite diez",
    eachClass: "cada clase",
    buyNow: "Comprar ahora",
    classesStartingFrom: "Clases desde $18 por clase",
    classLasts: "Cada clase dura 25 minutos",
    registerPurchaseNow: "¡Quiero registrarme y comprar clases ahora!",
    registerTrialDesc: "Registra a tu hijo para una clase de prueba gratuita y compra más clases para reservar a tu profesor favorito en el día y hora de tu conveniencia.",
    noChargeReschedule: "Sin cargo cuando reprogramas o cancelas tu clase con suficiente aviso.",
    
    // Hiring Page
    weAreHiring: "¡ESTAMOS CONTRATANDO!",
    joinTeamDesc: "Únete a nuestro apasionado equipo de enseñanza y marca la diferencia en la vida de los estudiantes. Comparte tu experiencia e inspira a la próxima generación de aprendices.",
    workRemotely: "Trabajo remoto",
    flexibleHours: "Horarios flexibles",
    competitivePay: "Pago competitivo",
    applyNow: "Aplicar ahora",
    sendCvDesc: "Envíanos tu CV y nos pondremos en contacto",
    fullName: "Nombre completo",
    email: "Correo electrónico",
    phoneNumber: "Número de teléfono",
    country: "País",
    uploadCv: "Subir CV (PDF/DOC)",
    chooseFile: "Elegir archivo",
    noFileSelected: "Ningún archivo seleccionado",
    coverLetter: "Carta de presentación (Opcional)",
    tellUsAboutYourself: "Cuéntanos sobre ti...",
    agreeToTerms: "Acepto los",
    and: "y",
    submitApplication: "Enviar solicitud",
    whyJoinTeam: "¿Por qué unirte a nuestro equipo?",
    buildingSomethingSpecial: "Estamos construyendo algo especial y queremos que educadores apasionados sean parte de ello",
    energeticTeachers: "Profesores enérgicos y entusiastas bienvenidos",
    energeticTeachersDesc1: "Creamos lecciones cortas e interactivas y nos preocupamos profundamente por la calidad de la enseñanza. Si disfrutas ayudar a los estudiantes a crecer, nos encantaría saber de ti.",
    energeticTeachersDesc2: "Comparte tu experiencia, tu disponibilidad y una breve presentación. Nuestro equipo revisará tu solicitud y te contactará si hay una coincidencia.",
    workWhenWhere: "Trabaja cuando y donde quieras",
    workWhenWhereDesc1: "Enseña en línea desde casa con materiales de lección estructurados. Tendrás orientación clara, apoyo de nuestro equipo y un proceso simple para programar.",
    workWhenWhereDesc2: "Nos enfocamos en la calidad: las lecciones se revisan y compartimos sugerencias de coaching para que los profesores puedan mejorar continuamente.",
    teacherProfile: "Perfil de los profesores",
    excellentSpeakers: "Excelentes oradores",
    universityDegree: "Carrera universitaria",
    patientKindFun: "Pacientes, amables y sobre todo divertidos",
    experienceWithChildren: "Experiencia en el trato con niños",
    availability: "Disponibilidad entre 3:30PM - 12:30AM (horario estadounidense) durante la semana, y 9:00AM - 12:30AM los fines de semana",
    reliableInternet: "Conexión a Internet fiable y de alta velocidad",
    wellLitSpace: "Lugar bien iluminado, sin ruido, tranquilo y sin interrupciones",
    punctualOrganized: "Imprescindible ser puntual y organizado",
    ifYouFitProfile: "¿Si encajas en el perfil, no lo dudes más!",
    fillFormContact: "Rellena el formulario y nos pondremos en contacto contigo",
    joinKidsClub: "¡Únete a la diversión con Kids' Club!",
    
    // Contact Page
    contactUsTitle: "Contáctanos",
    contactUsDesc: "¿Tienes preguntas? Nos encantaría saber de ti. Envíanos un mensaje y te responderemos lo antes posible.",
    emailUs: "Envíanos un correo",
    callUs: "Llámanos",
    visitUs: "Visítanos",
    workingHours: "Horario de atención",
    workingHoursTime: "Lun-Vie: 8AM-6PM",
    getInTouch: "¡Ponte en contacto con nosotros!",
    bestLearningExperience: "Estamos trabajando para ofrecerte la mejor experiencia de aprendizaje.",
    freeTrialClass: "Si quieres obtener una clase de prueba gratis",
    receiveInformation: "Si quieres recibir información sobre nuestros métodos y programas",
    latestCourses: "Si quieres estar actualizado con nuestros últimos cursos",
    moreInformation: "Para más información, contáctanos en:",
    followSocialMedia: "Síguenos en redes sociales:",
    sendMessage: "Envíanos un mensaje",
    emailNotPublished: "Tu dirección de correo electrónico no será publicada. Los campos obligatorios están marcados con *.",
    
    // Register Page
    studentRegistration: "Registro de estudiante",
    joinLearningCommunity: "Únete a nuestra comunidad de aprendizaje y comienza tu viaje en español hoy",
    alreadyRegistered: "¿Ya estás registrado?",
    signIn: "Iniciar sesión",
    account: "Cuenta",
    verifyEmailStep: "Verificar correo",
    parentInfo: "Información del padre",
    studentInfo: "Información del estudiante",
    password: "Contraseña",
    atLeast6Characters: "Al menos 6 caracteres",
    continue: "Continuar",
    creatingAccount: "Creando cuenta...",
    byContinuing: "Al continuar, aceptas nuestros",
    verifyYourEmail: "Verifica tu correo electrónico",
    checkEmailForCode: "Revisa tu correo electrónico para el código de 6 dígitos e ingrésalo a continuación.",
    resendCode: "Reenviar código",
    sending: "Enviando...",
    verificationCode: "Código de verificación",
    back: "Atrás",
    verifying: "Verificando...",
    verifyAndContinue: "Verificar y continuar",
    parentInformation: "Información del padre",
    tellUsWhoToContact: "Dinos con quién debemos contactar.",
    firstName: "Nombre",
    lastName: "Apellido",
    contactPhoneOptional: "Número de teléfono de contacto (opcional)",
    studentInformation: "Información del estudiante",
    fewDetailsForLessons: "Algunos detalles para que podamos adaptar las lecciones.",
    studentNameOrNickname: "Nombre o apodo del estudiante",
    birthdate: "Fecha de nacimiento",
    month: "Mes",
    day: "Día",
    year: "Año",
    helpsTailorLessonPacing: "Esto nos ayuda a adaptar el ritmo de las lecciones para tu hijo.",
    spanishLevel: "Nivel de español",
    selectLevel: "Seleccionar nivel",
    beginner: "Principiante",
    elementary: "Elemental",
    intermediate: "Intermedio",
    advanced: "Avanzado",
    canStudentRead: "¿El estudiante puede leer?",
    select: "Seleccionar",
    yes: "Sí",
    no: "No",
    homeschoolFundingQuestion: "¿El estudiante está inscrito en un programa de financiamiento estatal o charter de educación en casa?",
    studentQuestionnaire: "Cuestionario del estudiante",
    tellUsAboutGoals: "Cuéntanos sobre objetivos, experiencia y cualquier desafío...",
    done: "Hecho",
    congratulations: "¡Felicidades!",
    registrationComplete: "Tu registro está completo. Continuemos a eBlueLearning.",
    close: "Cerrar",
    verificationCodeTitle: "Código de verificación",
    useThisCodeToVerify: "Usa este código para verificar",
    copyCode: "Copiar código",
    
    // Login Page
    loginTitle: "Iniciar sesión",
    studentLoginDesc: "Inicio de sesión de estudiante (el correo electrónico debe estar verificado).",
    needAnAccount: "¿Necesitas una cuenta?",
    headsUp: "Aviso",
    emailNotVerifiedYet: "Tu correo electrónico aún no está verificado. Reenvía el código y verifica a través del flujo de registro.",
    goToVerify: "Ir a verificar",
    yourPassword: "Tu contraseña",
    show: "Mostrar",
    hide: "Ocultar",
    signingIn: "Iniciando sesión...",
    newHere: "¿Nuevo aquí?",
    verificationCodeResent: "Código de verificación reenviado. Revisa tu correo electrónico.",
    couldNotResendCode: "No se pudo reenviar el código.",
    
    // Teacher Availability Page
    availability: "Disponibilidad",
    manageScheduleDesc: "Gestiona tu horario semanal y bloques de tiempo únicos",
    refresh: "Actualizar",
    weeklySchedule: "Horario semanal",
    weeklyScheduleDesc: "Establece disponibilidad recurrente para días y horarios específicos",
    weekday: "Día de la semana",
    timezone: "Zona horaria",
    startTime: "Hora de inicio",
    endTime: "Hora de fin",
    adding: "Agregando...",
    addWeeklyBlock: "Agregar bloque semanal",
    timeOverride: "Anulación de tiempo",
    timeOverrideDesc: "Bloquea o agrega disponibilidad para fechas y horarios específicos",
    startDateTime: "Fecha y hora de inicio",
    endDateTime: "Fecha y hora de fin",
    status: "Estado",
    blockedUnavailable: "Bloqueado (No disponible)",
    available: "Disponible",
    addOverride: "Agregar anulación",
    currentAvailability: "Disponibilidad actual",
    currentAvailabilityDesc: "Todos tus bloques de disponibilidad programados",
    weeklyScheduleItem: "Horario semanal",
    blockedTime: "Tiempo bloqueado",
    availableTime: "Tiempo disponible",
    delete: "Eliminar",
    noAvailabilitySet: "Aún no se ha establecido disponibilidad. Agrega bloques semanales o anulaciones arriba.",
    timezoneNote: "La zona horaria se almacena pero la generación de slots actualmente se basa en UTC. Los bloques semanales se repiten cada semana, mientras que las anulaciones se aplican a fechas específicas.",
    loading: "Cargando...",
    
    // Weekdays
    sunday: "Domingo",
    monday: "Lunes",
    tuesday: "Martes",
    wednesday: "Miércoles",
    thursday: "Jueves",
    friday: "Viernes",
    saturday: "Sábado",
    
    // Teacher Bookings Page
    manageBookingsDesc: "Gestiona las reservas de tus clases y escribe informes de estudiantes",
    upcoming: "Próximas",
    history: "Historial",
    upcomingDesc: "Lecciones programadas. Selecciona una para unirte o marcar como completada.",
    historyDesc: "Lecciones completadas. Ver informes y estado de calificación.",
    student: "Estudiante",
    credits: "créditos",
    sessionNotScheduled: "Sesión no programada",
    ending: "Finalizando...",
    doneLesson: "Lección completada",
    rateStudent: "Calificar estudiante",
    join: "Unirse",
    noMeetingLink: "No hay enlace de reunión disponible",
    noCompletedLessons: "Aún no hay lecciones completadas. El historial aparecerá aquí.",
    noUpcomingBookings: "Aún no hay reservas próximas",
    classReport: "Informe de clase",
    classReportDesc: "Documenta el progreso del estudiante y asigna tareas",
    selectBookingToWriteReport: "Selecciona una reserva para escribir un informe",
    chatWithStudent: "Chatear con estudiante",
    messageStudent: "Mensaje al estudiante",
    editReport: "Editar informe",
    classSummary: "Resumen de clase",
    classSummaryPlaceholder: "Describe lo que se cubrió en esta clase...",
    studentStrengths: "Fortalezas del estudiante",
    studentStrengthsPlaceholder: "¿Qué hizo bien el estudiante?",
    homeworkAssignment: "Tarea asignada",
    homeworkPlaceholder: "Asigna tareas o actividades de práctica...",
    saving: "Guardando...",
    saveReport: "Guardar informe",
    updateReport: "Actualizar informe",
    rateThisLesson: "Calificar esta lección",
    howWasParticipation: "¿Cómo fue la participación de {student}?",
    commentOptional: "Comentario (opcional)",
    feedbackPlaceholder: "Cualquier comentario para el estudiante...",
    cancel: "Cancelar",
    submitting: "Enviando...",
    submitRating: "Enviar calificación",
    savedSuccessfully: "¡Guardado exitosamente! El estudiante ha sido notificado.",
    
    // Teacher Earnings Page
    earnings: "Ganancias",
    trackBookingsDesc: "Rastrea tus reservas y resumen de ganancias",
    bookingStatistics: "Estadísticas de reservas",
    bookingStatsDesc: "Resumen de las reservas de tus clases y ganancias",
    booked: "Reservadas",
    completed: "Completadas",
    cancelled: "Canceladas",
    noShow: "No se presentó",
    totalEarnings: "Ganancias totales",
    totalClasses: "Clases totales",
    payoutInfoNote: "Este es un resumen simple basado en reservas. La información detallada de pagos estará disponible en futuras actualizaciones.",
    
    // Teacher Booking Detail Page
    bookingDetails: "Detalles de la reserva",
    backToBookings: "Volver a reservas",
    bookingId: "ID de reserva",
    bookingStatus: "Estado de reserva",
    studentDetails: "Detalles del estudiante",
    sessionDetails: "Detalles de la sesión",
    sessionTime: "Hora de la sesión",
    meetingLink: "Enlace de reunión",
    bookingDate: "Fecha de reserva",
    creditsCost: "Costo en créditos",
    teacherActions: "Acciones del profesor",
    viewReport: "Ver informe",
    writeReport: "Escribir informe",
    ratingStatus: "Estado de calificación",
    rated: "Calificado",
    notRated: "No calificado",
    bookingNotFound: "Reserva no encontrada",
    bookingNotFoundDesc: "La reserva que buscas no existe o no tienes permisos para verla.",
    
    // Teacher Login Page
    teacherLogin: "Inicio de sesión de profesor",
    teacherLoginDesc: "Inicio de sesión de profesor (el correo electrónico debe estar verificado).",
    needTeacherAccount: "¿Necesitas una cuenta de profesor?",
    notTeacherAccount: "Esta cuenta no es una cuenta de profesor.",
    emailNotVerifiedTeacher: "Tu correo electrónico aún no está verificado. Reenvía el código y verifica en la página de Registro de Profesor.",
    goToVerify: "Ir a verificar",
    teacher: "Profesor",
  },
  en: {
    // Main Header
    home: "Home",
    ourTeachers: "Our teachers",
    pricing: "Pricing",
    hiring: "Hiring",
    blog: "Blog",
    contact: "Contact",
    register: "Register",
    login: "Login",
    logout: "Logout",
    dashboard: "Dashboard",
    joinNow: "Start your adventure",
    watchTrailer: "Watch demo",
    heroTitle: "St. George English",
    heroSubtitle: "Learn English by exploring the universe",
    heroDescription: "Embark on a linguistic journey across the English Galaxy. No textbooks, no boring lectures—just pure interstellar exploration.",
    
    // Dashboard Header
    teacher: "Teacher",
    sessions: "Sessions",
    bookings: "Bookings",
    availabilityMenu: "Availability",
    earnings: "Earnings",
    forum: "Forum",
    moderation: "Moderation",
    yourClasses: "Your classes",
    bookClasses: "Book classes",
    bookByTeacher: "Book by teacher",
    bookByDate: "Book by date",
    credits: "Credits",
    buyCredits: "Buy credits",
    shareCredits: "Share credits",
    profile: "Profile",
    
    // Notifications
    notifications: "Notifications",
    viewAll: "View all",
    noNotifications: "No notifications yet.",
    markRead: "Mark read",
    
    // Home Page
    methodologyTitle: "St. George's Methodology",
    methodologyDesc: "Our exclusive Path to Fluency helps students learn English naturally, step by step.",
    stepListen: "Listen",
    stepListenDesc: "Understand natural, real-life English through immersive listening practice.",
    stepSpeak: "Speak",
    stepSpeakDesc: "Express ideas clearly and build confidence in everyday conversations.",
    stepWrite: "Write",
    stepWriteDesc: "Communicate effectively in written form with guided exercises.",
    stepRead: "Read",
    stepReadDesc: "Build vocabulary and internalize grammar through engaging reading.",
    whyStGeorge: "Why St. George's?",
    whyStGeorgeDesc: "We combine proven methodology with space-themed fun so every student stays motivated and makes real progress.",
    personalizedPaths: "Personalized learning paths",
    qualifiedTeachers: "Qualified native teachers",
    missionBasedLessons: "Mission-based lessons",
    exploreLessons: "Explore lessons",
    seriouslyFunTitle: "Our lessons are seriously fun",
    seriouslyFunDesc1: "Our English missions are designed to keep attention with short lessons, simple practice, and quick quizzes.",
    seriouslyFunDesc2: "Learn anywhere, anytime — and build vocabulary and confidence step by step.",
    seriouslyFunDesc3: "You'll be learning so much you won't even notice you're studying.",
    methodologyFullTitle: "St. George's Methodology",
    methodologyFullDesc1: "At St. George, we use our exclusive methodology called",
    pathToFluency: "Path to Fluency",
    methodologyFullDesc2: "designed to help students learn English in a natural, structured, and engaging way—just like acquiring their first language.",
    methodologyFullDesc3: "What truly makes our method unique is that we design our own materials, adapted to the age and knowledge level of each student.",
    methodologyFullDesc4: "This personalized and hands-on approach ensures that every class is not only effective, but also",
    methodologyFullDesc5: "fun, motivating, and meaningful",
    methodologyFullDesc6: "so students enjoy the process as they become fluent in English.",
    selectTimeTitle: "Select your study time, day, and mission",
    selectTimeDesc1: "No travel needed — learn from home with short, focused practice.",
    selectTimeDesc2: "Choose a lesson, follow the examples, then quiz yourself.",
    startLearning: "Start Learning!",
    customMaterialsTitle: "Custom Materials for Every Student",
    customMaterialsDesc: "We design our own resources, adapted to the age and knowledge level of each student.",
    illustratedFlashcards: "Illustrated Flashcards",
    themedGames: "Themed Games",
    interactiveWorksheets: "Interactive Worksheets",
    educationalBoardGames: "Educational Board Games",
    gamifiedActivities: "Gamified Activities",
    startFirstMission: "Start your first mission",
    bridgingGapTitle: "Bridging the Gap",
    bridgingGapDesc: "Guided missions that make learning feel simple and fun.",
    kidTestedTitle: "Kid Tested",
    kidTestedDesc: "Short lessons designed to keep attention and build confidence.",
    onlineNewHomeTitle: "Online is the New Home",
    onlineNewHomeDesc: "Learn anywhere and check your progress with quick quizzes.",
    moreAboutMissions: "More About Our English Missions",
    lookNoFurtherTitle: "Look no further\nGet started today!",
    lookNoFurtherDesc1: "Start with short lessons, learn useful vocabulary, and finish with quick quizzes. Perfect for daily practice.",
    lookNoFurtherDesc2: "Learn anywhere, anytime — and build confidence step by step.",
    joinNowCta: "Join Now!",
    
    // Testimonials
    whatLearnersSay: "What learners say",
    leaveReviewGoogle: "Leave us a review on Google",
    readMore: "Read more",
    of: "of",
    
    // Footer
    keepLearning: "Keep Learning",
    smallStepsEveryDay: "Small steps, every day",
    quickLinks: "Quick Links",
    lessons: "Lessons",
    quizzes: "Quizzes",
    vocabulary: "Vocabulary",
    aboutUs: "About Us",
    aboutStGeorge: "About St. George",
    ourMethodology: "Our Methodology",
    contactUs: "Contact Us",
    communityForum: "Community Forum",
    faq: "FAQ",
    getStarted: "Get Started",
    getStartedDesc: "Start your English learning journey today with our interactive lessons and expert teachers.",
    bookFreeTrial: "Book Free Trial",
    copyright: "Copyright",
    allRightsReserved: "All Rights Reserved",
    termsConditions: "Terms & Conditions",
    legalAdvisory: "Legal Advisory",
    privacyPolicy: "Privacy Policy",
    
    // Our Teachers Page
    ourTeachersTitle: "Our Teachers",
    ourTeachersDesc: "Learn English in a natural and practical context by studying real-life situations that will allow you to excel in the language. Our teaching materials are designed to make our classes not only informative but also incredibly entertaining. Furthermore, we adapt our curriculum to each student's age, ensuring that learning is both natural and fascinating. Join us now and experience the most engaging and effective English training program available!",
    bookFreeTrialNow: "Book a free trial class now!",
    viewPricing: "View pricing",
    teacherSelectionTitle: "Our Teacher Selection Process",
    teacherSelectionDesc: "We recognize that our method is unique and special, and our expectations for classes are very high.",
    selectionProcess: "Selection Process",
    selectionProcessDesc: "We select teachers for clarity, patience, and kid-friendly communication.",
    energyCharisma: "Energy and Charisma",
    energyCharismaDesc: "Lessons are lively and engaging to keep attention from start to finish.",
    highEnergy: "High Energy",
    highEnergyDesc: "Interactive practice makes learners participate—not just watch.",
    childAttention: "Child's Attention",
    childAttentionDesc: "Short missions and clear steps help build confidence quickly.",
    qualityMonitoringDesc: "We don't stop there. Our Head Teacher Coordinator and Head of Studies monitor classes for quality, suggest improvements, and coach teachers for continuous progress. We hold high standards and improve together with our teachers.",
    meetTeachersTitle: "Meet a few of our English teachers",
    experiencedEducators: "Experienced educators from around the world",
    englishTeacher: "English Teacher",
    ourSecretary: "Our secretary",
    socialMediaManager: "Social Media Manager",
    contentDeveloper: "Educational Content Developer",
    joinClubCta: "It's English time!! Join our club!!",
    
    // Pricing Page
    admitOne: "Admit one",
    admitFive: "Admit five",
    admitTen: "Admit ten",
    eachClass: "each class",
    buyNow: "Buy Now",
    classesStartingFrom: "Classes starting from $18 per class",
    classLasts: "Each class lasts 25 minutes",
    registerPurchaseNow: "I want to Register and Purchase Classes Now!",
    registerTrialDesc: "Register your child for a free trial class and purchase more classes to book your favorite teacher at the day and time of your convenience.",
    noChargeReschedule: "No charge when you reschedule or cancel your class with enough notice.",
    
    // Hiring Page
    weAreHiring: "WE'RE HIRING!",
    joinTeamDesc: "Join our passionate teaching team and make a difference in students' lives. Share your expertise and inspire the next generation of learners.",
    workRemotely: "Work Remotely",
    flexibleHours: "Flexible Hours",
    competitivePay: "Competitive Pay",
    applyNow: "Apply Now",
    sendCvDesc: "Send us your CV and we'll be in touch",
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    country: "Country",
    uploadCv: "Upload CV (PDF/DOC)",
    chooseFile: "Choose File",
    noFileSelected: "No file selected",
    coverLetter: "Cover Letter (Optional)",
    tellUsAboutYourself: "Tell us about yourself...",
    agreeToTerms: "I agree to the",
    and: "and",
    submitApplication: "Submit Application",
    whyJoinTeam: "Why Join Our Team?",
    buildingSomethingSpecial: "We're building something special, and we want passionate educators to be part of it",
    energeticTeachers: "Energetic & Enthusiastic Teachers Welcome",
    energeticTeachersDesc1: "We create short, interactive lessons and we care deeply about teaching quality. If you enjoy helping learners grow, we'd love to hear from you.",
    energeticTeachersDesc2: "Share your experience, your availability, and a short introduction. Our team will review your application and contact you if there's a match.",
    workWhenWhere: "Work When & Where You Want",
    workWhenWhereDesc1: "Teach online from home with structured lesson materials. You'll have clear guidance, support from our team, and a simple process for scheduling.",
    workWhenWhereDesc2: "We focus on quality: lessons are reviewed and we share coaching suggestions so teachers can improve continuously.",
    teacherProfile: "Teacher Profile",
    excellentSpeakers: "Excellent speakers",
    universityDegree: "University degree",
    patientKindFun: "Patient, kind and above all fun",
    experienceWithChildren: "Experience working with children",
    availability: "Availability between 3:30PM - 12:30AM (US time) during the week, and 9:00AM - 12:30AM on weekends",
    reliableInternet: "Reliable and high-speed Internet connection",
    wellLitSpace: "Well-lit, quiet, noise-free space without interruptions",
    punctualOrganized: "Must be punctual and organized",
    ifYouFitProfile: "If you fit the profile, don't hesitate!",
    fillFormContact: "Fill out the form and we'll get in touch with you",
    joinKidsClub: "Join the Fun with Kids' Club!",
    
    // Contact Page
    contactUsTitle: "Contact Us",
    contactUsDesc: "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    emailUs: "Email Us",
    callUs: "Call Us",
    visitUs: "Visit Us",
    workingHours: "Working Hours",
    workingHoursTime: "Mon-Fri: 8AM-6PM",
    getInTouch: "Get in touch with us!",
    bestLearningExperience: "We are working on offering you the best learning experience.",
    freeTrialClass: "If you want to get a free trial class",
    receiveInformation: "If you want to receive information about our methods and programs",
    latestCourses: "If you want to be updated with our latest courses",
    moreInformation: "For more information, contact us at:",
    followSocialMedia: "Follow us on social media:",
    sendMessage: "Send us a message",
    emailNotPublished: "Your email address will not be published. Required fields are marked with *.",
    
    // Register Page
    studentRegistration: "Student Registration",
    joinLearningCommunity: "Join our learning community and start your Spanish journey today",
    alreadyRegistered: "Already registered?",
    signIn: "Sign In",
    account: "Account",
    verifyEmailStep: "Verify Email",
    parentInfo: "Parent Info",
    studentInfo: "Student Info",
    password: "Password",
    atLeast6Characters: "At least 6 characters",
    continue: "Continue",
    creatingAccount: "Creating account...",
    byContinuing: "By continuing, you agree to our",
    verifyYourEmail: "Verify your email",
    checkEmailForCode: "Check your email for the 6-digit code and enter it below.",
    resendCode: "Resend code",
    sending: "Sending...",
    verificationCode: "Verification code",
    back: "Back",
    verifying: "Verifying...",
    verifyAndContinue: "Verify & Continue",
    parentInformation: "Parent information",
    tellUsWhoToContact: "Tell us who we should contact.",
    firstName: "First Name",
    lastName: "Last Name",
    contactPhoneOptional: "Contact phone number (optional)",
    studentInformation: "Student information",
    fewDetailsForLessons: "A few details so we can tailor lessons.",
    studentNameOrNickname: "Student Name or Nickname",
    birthdate: "Birthdate",
    month: "Month",
    day: "Day",
    year: "Year",
    helpsTailorLessonPacing: "This helps us tailor lesson pacing for your child.",
    spanishLevel: "Spanish Level",
    selectLevel: "Select level",
    beginner: "Beginner",
    elementary: "Elementary",
    intermediate: "Intermediate",
    advanced: "Advanced",
    canStudentRead: "Can the student read?",
    select: "Select",
    yes: "Yes",
    no: "No",
    homeschoolFundingQuestion: "Is the student enrolled in a Homeschool Charter or state funding program?",
    studentQuestionnaire: "Student Questionnaire",
    tellUsAboutGoals: "Tell us about goals, experience, and any challenges...",
    done: "Done",
    congratulations: "Congratulations!",
    registrationComplete: "Your registration is complete. Let's continue to eBlueLearning.",
    close: "Close",
    verificationCodeTitle: "Verification code",
    useThisCodeToVerify: "Use this code to verify",
    copyCode: "Copy code",
    
    // Login Page
    loginTitle: "Login",
    studentLoginDesc: "Student login (email must be verified).",
    needAnAccount: "Need an account?",
    headsUp: "Heads up",
    emailNotVerifiedYet: "Your email is not verified yet. Resend the code and verify via the Register flow.",
    goToVerify: "Go to verify",
    yourPassword: "Your password",
    show: "Show",
    hide: "Hide",
    signingIn: "Signing in...",
    newHere: "New here?",
    verificationCodeResent: "Verification code resent. Check your email.",
    couldNotResendCode: "Could not resend code.",
    
    // Teacher Availability Page
    availability: "Availability",
    manageScheduleDesc: "Manage your weekly schedule and one-off time blocks",
    refresh: "Refresh",
    weeklySchedule: "Weekly Schedule",
    weeklyScheduleDesc: "Set recurring availability for specific days and times",
    weekday: "Weekday",
    timezone: "Timezone",
    startTime: "Start Time",
    endTime: "End Time",
    adding: "Adding...",
    addWeeklyBlock: "Add Weekly Block",
    timeOverride: "Time Override",
    timeOverrideDesc: "Block or add availability for specific dates and times",
    startDateTime: "Start Date & Time",
    endDateTime: "End Date & Time",
    status: "Status",
    blockedUnavailable: "Blocked (Unavailable)",
    available: "Available",
    addOverride: "Add Override",
    currentAvailability: "Current Availability",
    currentAvailabilityDesc: "All your scheduled availability blocks",
    weeklyScheduleItem: "Weekly Schedule",
    blockedTime: "Blocked Time",
    availableTime: "Available Time",
    delete: "Delete",
    noAvailabilitySet: "No availability set yet. Add weekly blocks or overrides above.",
    timezoneNote: "Timezone is stored but slot generation is currently UTC-based. Weekly blocks repeat every week, while overrides apply to specific dates.",
    loading: "Loading...",
    
    // Weekdays
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    
    // Teacher Bookings Page
    // bookings: "Bookings",
    manageBookingsDesc: "Manage your class bookings and write student reports",
    upcoming: "Upcoming",
    history: "History",
    upcomingDesc: "Scheduled lessons. Select one to join or mark done.",
    historyDesc: "Completed lessons. View reports and rating status.",
    student: "Student",
    credits: "credits",
    sessionNotScheduled: "Session not scheduled",
    ending: "Ending…",
    doneLesson: "Done lesson",
    rateStudent: "Rate student",
    join: "Join",
    noMeetingLink: "No meeting link available",
    noCompletedLessons: "No completed lessons yet. History will appear here.",
    noUpcomingBookings: "No upcoming bookings yet",
    classReport: "Class Report",
    classReportDesc: "Document the student's progress and assign homework",
    selectBookingToWriteReport: "Select a booking to write a report",
    chatWithStudent: "Chat with student",
    messageStudent: "Message student",
    editReport: "Edit Report",
    classSummary: "Class Summary",
    classSummaryPlaceholder: "Describe what was covered in this class...",
    studentStrengths: "Student Strengths",
    studentStrengthsPlaceholder: "What did the student do well?",
    homeworkAssignment: "Homework Assignment",
    homeworkPlaceholder: "Assign homework or practice activities...",
    saving: "Saving...",
    saveReport: "Save Report",
    updateReport: "Update Report",
    rateThisLesson: "Rate this lesson",
    howWasParticipation: "How was {student}'s participation?",
    commentOptional: "Comment (optional)",
    feedbackPlaceholder: "Any feedback for the student...",
    cancel: "Cancel",
    submitting: "Submitting…",
    submitRating: "Submit rating",
    savedSuccessfully: "Saved successfully! The student has been notified.",
    
    // Teacher Earnings Page
    earnings: "Earnings",
    trackBookingsDesc: "Track your bookings and earnings summary",
    bookingStatistics: "Booking Statistics",
    bookingStatsDesc: "Overview of your class bookings and earnings",
    booked: "Booked",
    completed: "Completed",
    cancelled: "Cancelled",
    noShow: "No Show",
    totalEarnings: "Total Earnings",
    totalClasses: "Total Classes",
    payoutInfoNote: "This is a simple summary based on bookings. Detailed payout information will be available in future updates.",
    
    // Teacher Booking Detail Page
    bookingDetails: "Booking Details",
    backToBookings: "Back to Bookings",
    bookingId: "Booking ID",
    bookingStatus: "Booking Status",
    studentDetails: "Student Details",
    sessionDetails: "Session Details",
    sessionTime: "Session Time",
    meetingLink: "Meeting Link",
    bookingDate: "Booking Date",
    creditsCost: "Credits Cost",
    teacherActions: "Teacher Actions",
    viewReport: "View Report",
    writeReport: "Write Report",
    ratingStatus: "Rating Status",
    rated: "Rated",
    notRated: "Not Rated",
    bookingNotFound: "Booking Not Found",
    bookingNotFoundDesc: "The booking you're looking for doesn't exist or you don't have permission to view it.",
    
    // Teacher Login Page
    teacherLogin: "Teacher Login",
    teacherLoginDesc: "Teacher login (email must be verified).",
    needTeacherAccount: "Need a teacher account?",
    notTeacherAccount: "This account is not a teacher account.",
    emailNotVerifiedTeacher: "Your email is not verified yet. Resend the code and verify on the Teacher Register page.",
    goToVerify: "Go to verify",
    teacher: "Teacher",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");

  useEffect(() => {
    const saved = localStorage.getItem("app_language") as Language | null;
    if (saved === "es" || saved === "en") {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app_language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.es] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
