export type SupportedLanguage = "en" | "es";

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // List page
    latestPosts: "Latest Posts",
    newPost: "New Post",
    searchPlaceholder: "Search articles by title...",
    search: "Search",
    myPosts: "My Posts",
    loading: "Loading...",
    author: "Author",
    unknown: "Unknown",
    discussion: "Discussion",
    replies: "replies",
    views: "views",
    lastReply: "Last reply",
    noArticlesFound: "No articles found.",
    timeAgoM: "m ago",
    timeAgoH: "h ago",
    timeAgoD: "d ago",

    // Me page
    forum: "Forum",
    backToForum: "Back to Forum",
    admin: "Admin",
    remaining: "Remaining",
    forumCredits: "Forum credits",
    used: "Used",
    myArticles: "My articles",
    noSubmissionsYet: "No submissions yet.",
    reason: "Reason",
    followedArticles: "Followed articles",
    followed: "Followed",
    article: "Article",
    notFollowingAny: "You are not following any articles yet.",
    notifications: "Notifications",
    unread: "unread",
    open: "Open",
    markRead: "Mark read",
    noNotificationsYet: "No notifications yet.",

    // New post page
    back: "Back",
    postTitle: "Post Title",
    postTitlePlaceholder: "Enter post title...",
    characters: "characters",
    postContent: "Post Content",
    postContentSupports: "Supports Markdown",
    edit: "Edit",
    preview: "Preview",
    publish: "Publish",
    publishing: "Publishing...",
    contentPlaceholder: "Enter post content, supports Markdown syntax...",
    previewPlaceholder: "Preview will appear here...",
    note: "Note",
    moderationNote:
      "Your post will be reviewed by moderators before being published. You'll be notified once it's approved or if any changes are needed.",
    failedToCreateArticle: "Failed to create article",

    // Article detail [id]
    articleNotFound: "Article not found",
    unfollow: "Unfollow",
    follow: "Follow",
    commentsCount: "Comments",
    writeCommentPlaceholder: "Write your comment...",
    posting: "Posting...",
    postComment: "Post Comment",
    like: "Like",
    reply: "Reply",
    noCommentsYet: "No comments yet. Be the first to comment!",
    failedToUpdateReaction: "Failed to update reaction",

    // Admin page
    forumAdmin: "Forum admin",
    forumAdminDesc: "Approve posts and moderate uploads.",
    refresh: "Refresh",
    pendingArticles: "Pending articles",
    review: "Review",
    approve: "Approve",
    rejectionReasonPlaceholder: "Rejection reason...",
    reject: "Reject",
    noPendingArticles: "No pending articles.",
    pendingAttachments: "Pending attachments",
    noPendingAttachments: "No pending attachments.",
    awardForumCredits: "Award forum credits",
    userObjectIdPlaceholder: "User ObjectId",
    reasonOptional: "Reason (optional)",
    award: "Award",
    banUser: "Ban user",
    banDisable: "Ban (disable)",
    unbanUser: "Unban user",
    unbanActivate: "Unban (activate)",
    provideRejectionReason: "Please provide a rejection reason.",
    provideAttachmentRejectionReason: "Please provide an attachment rejection reason.",
  },
  es: {
    latestPosts: "Últimas publicaciones",
    newPost: "Nueva publicación",
    searchPlaceholder: "Buscar artículos por título...",
    search: "Buscar",
    myPosts: "Mis publicaciones",
    loading: "Cargando...",
    author: "Autor",
    unknown: "Desconocido",
    discussion: "Discusión",
    replies: "respuestas",
    views: "vistas",
    lastReply: "Última respuesta",
    noArticlesFound: "No se encontraron artículos.",
    timeAgoM: " min",
    timeAgoH: " h",
    timeAgoD: " d",

    myArticles: "Mis artículos",
    forum: "Foro",
    backToForum: "Volver al foro",
    admin: "Administración",
    remaining: "Restantes",
    forumCredits: "Créditos del foro",
    used: "Usados",
    noSubmissionsYet: "Aún no hay envíos.",
    reason: "Motivo",
    followedArticles: "Artículos seguidos",
    followed: "Seguido",
    article: "Artículo",
    notFollowingAny: "Aún no sigues ningún artículo.",
    notifications: "Notificaciones",
    unread: "sin leer",
    open: "Abrir",
    markRead: "Marcar como leído",
    noNotificationsYet: "Aún no hay notificaciones.",

    back: "Atrás",
    postTitle: "Título de la publicación",
    postTitlePlaceholder: "Escribe el título...",
    characters: "caracteres",
    postContent: "Contenido de la publicación",
    postContentSupports: "Soporta Markdown",
    edit: "Editar",
    preview: "Vista previa",
    publish: "Publicar",
    publishing: "Publicando...",
    contentPlaceholder: "Escribe el contenido, soporta sintaxis Markdown...",
    previewPlaceholder: "La vista previa aparecerá aquí...",
    note: "Nota",
    moderationNote:
      "Tu publicación será revisada por los moderadores antes de publicarse. Recibirás una notificación cuando se apruebe o si se necesitan cambios.",
    failedToCreateArticle: "Error al crear la publicación",

    articleNotFound: "Artículo no encontrado",
    unfollow: "Dejar de seguir",
    follow: "Seguir",
    commentsCount: "Comentarios",
    writeCommentPlaceholder: "Escribe tu comentario...",
    posting: "Publicando...",
    postComment: "Publicar comentario",
    like: "Me gusta",
    reply: "Responder",
    noCommentsYet: "Aún no hay comentarios. ¡Sé el primero!",
    failedToUpdateReaction: "Error al actualizar la reacción",

    forumAdmin: "Administración del foro",
    forumAdminDesc: "Aprueba publicaciones y modera subidas.",
    refresh: "Actualizar",
    pendingArticles: "Artículos pendientes",
    review: "Revisar",
    approve: "Aprobar",
    rejectionReasonPlaceholder: "Motivo del rechazo...",
    reject: "Rechazar",
    noPendingArticles: "No hay artículos pendientes.",
    pendingAttachments: "Adjuntos pendientes",
    noPendingAttachments: "No hay adjuntos pendientes.",
    awardForumCredits: "Otorgar créditos del foro",
    userObjectIdPlaceholder: "ObjectId del usuario",
    reasonOptional: "Motivo (opcional)",
    award: "Otorgar",
    banUser: "Suspender usuario",
    banDisable: "Suspender (desactivar)",
    unbanUser: "Reactivar usuario",
    unbanActivate: "Reactivar",
    provideRejectionReason: "Indica un motivo de rechazo.",
    provideAttachmentRejectionReason: "Indica un motivo de rechazo del adjunto.",
  },
};

/**
 * Translates a string key into the requested language.
 * Falls back to the original key when no translation is found.
 */
export function translate(key: string, language: SupportedLanguage = "en"): string {
  const table = translations[language];
  return (table && table[key]) || key;
}
