export type SupportedLanguage = "en" | "es";

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Dashboard
    dashboard: "Dashboard",
    overviewAndMetrics: "Overview and key metrics",
    failedToLoadStats: "Failed to load stats",
    failedToLoadDashboard: "Failed to load dashboard",
    totalUsers: "Total Users",
    newSignups: "New signups",
    totalBookings: "Total Bookings",
    bookings30d: "Bookings (30d)",
    fromPrevious30Days: "from previous 30 days",
    activityOverview: "Activity overview",
    last30Days: "Last 30 days",
    registrations: "Registrations",
    bookings: "Bookings",
    weeklyActivity: "Weekly activity",
    thisWeek: "This week",
    registrationsBookingsPerDay: "Registrations + bookings per day",
    recentRegistrations: "Recent registrations",
    viewAll: "View all",
    noRecentRegistrations: "No recent registrations",
    userBreakdown: "User breakdown",
    allTime: "All time",
    students: "Students",
    teachers: "Teachers",
    admins: "Admins",
    users: "Users",
    forum: "Forum",
    finance: "Finance",
    settings: "Settings",
    justNow: "Just now",
    timeAgoM: "m ago",
    timeAgoH: "h ago",
    timeAgoD: "d ago",

    // Login
    adminLogin: "Admin Login",
    signInToAccess: "Sign in to access the admin panel",
    emailAddress: "Email Address",
    password: "Password",
    emailPlaceholder: "admin@example.com",
    signingIn: "Signing in...",
    signIn: "Sign In",
    backToHome: "Back to Home",
    accessDenied: "Access denied. Admin privileges required.",

    // Users list
    userManagement: "User Management",
    manageUsersDesc: "Manage all users, roles, and permissions",
    refresh: "Refresh",
    search: "Search",
    searchByEmail: "Search by email...",
    role: "Role",
    allRoles: "All Roles",
    student: "Student",
    teacher: "Teacher",
    admin: "Admin",
    status: "Status",
    allStatus: "All Status",
    active: "Active",
    inactive: "Inactive",
    banned: "Banned",
    user: "User",
    credits: "Credits",
    joined: "Joined",
    actions: "Actions",
    loadingUsers: "Loading users...",
    noUsersFound: "No users found",
    edit: "Edit",
    ban: "Ban",
    showing: "Showing",
    to: "to",
    of: "of",
    results: "results",
    previous: "Previous",
    next: "Next",

    // User edit [id]
    loadingUser: "Loading user...",
    userNotFound: "User not found",
    editUser: "Edit User",
    updateUserDesc: "Update user information and permissions",
    userInformation: "User Information",
    userId: "User ID",
    created: "Created",
    lastLogin: "Last Login",
    emailVerified: "Email Verified",
    verified: "Verified",
    notVerified: "Not Verified",
    actionsLabel: "Actions",
    unbanUser: "Unban user",
    banUser: "Ban user",
    awardCredits: "Award credits",
    profile: "Profile",
    name: "Name",
    country: "Country",
    timezone: "Timezone",
    editUserDetails: "Edit User Details",
    changingRoleHint: "Changing role will affect user permissions and access",
    bannedUsersHint: "Banned users cannot log in to the platform",
    saving: "Saving...",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    awardCreditsTitle: "Award credits",
    amountLabel: "Amount (1–1000)",
    reasonOptional: "Reason (optional)",
    reasonPlaceholder: "e.g. Forum contribution",
    sending: "Sending...",
    award: "Award",
    userUpdatedSuccess: "User updated successfully!",
    userBannedSuccess: "User has been banned.",
    userUnbannedSuccess: "User has been unbanned.",
    creditsAwardedSuccess: "Credits awarded. New balance:",
    failedToBan: "Failed to ban user",
    failedToUnban: "Failed to unban user",
    failedToAwardCredits: "Failed to award credits",

    // Bookings
    bookingsManagement: "Bookings Management",
    viewManageBookings: "View and manage all class bookings",
    bookingId: "Booking ID",
    studentColumn: "Student",
    dateTime: "Date & Time",
    loadingBookings: "Loading bookings...",
    noBookingsFound: "No bookings found",
    view: "View",
    cancelAction: "Cancel",
    totalBookingsLabel: "Total Bookings",
    booked: "Booked",
    completed: "Completed",
    totalCredits: "Total Credits",
    noShow: "No Show",
    cancelled: "Cancelled",
    unknown: "Unknown",

    // Teachers
    teacherManagement: "Teacher Management",
    manageTeachersDesc: "Manage all teachers and their profiles",
    loadingTeachers: "Loading teachers...",
    noTeachersFound: "No teachers found",
    noNameSet: "No name set",
    joinedDate: "Joined",
    emailVerifiedLabel: "Email verified",
    viewProfile: "View Profile",
    moreActions: "More actions",
    editDetails: "Edit Details",
    suspendTeacher: "Suspend Teacher",
    activateTeacher: "Activate Teacher",
    banTeacher: "Ban Teacher",
    totalTeachers: "Total Teachers",
    verifiedEmail: "Verified Email",
    withProfile: "With Profile",

    // Finance
    financeTitle: "Finance",
    financeDesc: "Revenue, payouts, and financial overview",
    failedToLoadFinance: "Failed to load finance summary",
    loadingFinanceData: "Loading finance data…",
    estRevenueUsd: "Est. revenue (USD)",
    fromCreditPurchases: "From credit purchases (package pricing)",
    creditsPurchased: "Credits purchased",
    transactionsCount: "transaction(s)",
    creditsSpent: "Credits spent",
    onCompletedCancelled: "On completed/cancelled classes",
    creditsRefunded: "Credits refunded",
    cancellations: "Cancellations",
    creditsPurchasedLast30: "Credits purchased (last 30 days)",
    teacherEarningsCredits: "Teacher earnings (credits)",
    creditsEarned: "Credits earned",
    completedClasses: "Completed classes",
    noCompletedBookings: "No completed bookings yet.",
    recentCreditTransactions: "Recent credit transactions",
    date: "Date",
    type: "Type",
    amount: "Amount",
    method: "Method",
    userLabel: "User",
    noTransactions30Days: "No transactions in the last 30 days.",

    // Settings
    settingsTitle: "Settings",
    settingsDesc: "Admin panel and platform configuration",
    settingsComingSoon: "Settings module coming soon",
    settingsComingSoonDesc: "Here you will be able to configure site-wide options, feature flags, and admin preferences once the backend settings API is in place.",

    // Admin Forum
    forumManagement: "Forum Management",
    forumModerateDesc: "Moderate articles, attachments, and user actions",
    viewForum: "View Forum",
    pendingArticles: "Pending Articles",
    pendingAttachments: "Pending Attachments",
    userActions: "User Actions",
    loading: "Loading...",
    noPendingArticles: "No pending articles",
    review: "Review",
    approve: "Approve",
    rejectionReasonPlaceholder: "Rejection reason...",
    reject: "Reject",
    noPendingAttachments: "No pending attachments",
    open: "Open",
    awardCreditsTitleForum: "Award Credits",
    userIdLabel: "User ID",
    userObjectIdPlaceholder: "User ObjectId",
    amountLabelForum: "Amount",
    reasonOptionalForum: "Reason (optional)",
    reasonForAwarding: "Reason for awarding credits",
    awardCreditsButton: "Award Credits",
    banUserTitle: "Ban User",
    unbanUserTitle: "Unban User",
    provideRejectionReason: "Please provide a rejection reason.",
    provideAttachmentRejectionReason: "Please provide an attachment rejection reason.",
  },
  es: {
    dashboard: "Panel de control",
    overviewAndMetrics: "Resumen y métricas clave",
    failedToLoadStats: "Error al cargar estadísticas",
    failedToLoadDashboard: "Error al cargar el panel",
    totalUsers: "Total de usuarios",
    newSignups: "Nuevos registros",
    totalBookings: "Total de reservas",
    bookings30d: "Reservas (30 d)",
    fromPrevious30Days: "respecto a los 30 días anteriores",
    activityOverview: "Resumen de actividad",
    last30Days: "Últimos 30 días",
    registrations: "Registros",
    bookings: "Reservas",
    weeklyActivity: "Actividad semanal",
    thisWeek: "Esta semana",
    registrationsBookingsPerDay: "Registros + reservas por día",
    recentRegistrations: "Registros recientes",
    viewAll: "Ver todo",
    noRecentRegistrations: "No hay registros recientes",
    userBreakdown: "Desglose de usuarios",
    allTime: "Todo el tiempo",
    students: "Estudiantes",
    teachers: "Profesores",
    admins: "Administradores",
    users: "Usuarios",
    forum: "Foro",
    finance: "Finanzas",
    settings: "Configuración",
    justNow: "Ahora mismo",
    timeAgoM: "m atrás",
    timeAgoH: "h atrás",
    timeAgoD: "d atrás",

    adminLogin: "Inicio de sesión admin",
    signInToAccess: "Inicia sesión para acceder al panel de administración",
    emailAddress: "Correo electrónico",
    password: "Contraseña",
    emailPlaceholder: "admin@ejemplo.com",
    signingIn: "Iniciando sesión...",
    signIn: "Iniciar sesión",
    backToHome: "Volver al inicio",
    accessDenied: "Acceso denegado. Se requieren privilegios de administrador.",

    userManagement: "Gestión de usuarios",
    manageUsersDesc: "Gestionar usuarios, roles y permisos",
    refresh: "Actualizar",
    search: "Buscar",
    searchByEmail: "Buscar por correo...",
    role: "Rol",
    allRoles: "Todos los roles",
    student: "Estudiante",
    teacher: "Profesor",
    admin: "Administrador",
    status: "Estado",
    allStatus: "Todos los estados",
    active: "Activo",
    inactive: "Inactivo",
    banned: "Baneado",
    user: "Usuario",
    credits: "Créditos",
    joined: "Registrado",
    actions: "Acciones",
    loadingUsers: "Cargando usuarios...",
    noUsersFound: "No se encontraron usuarios",
    edit: "Editar",
    ban: "Banear",
    showing: "Mostrando",
    to: "a",
    of: "de",
    results: "resultados",
    previous: "Anterior",
    next: "Siguiente",

    loadingUser: "Cargando usuario...",
    userNotFound: "Usuario no encontrado",
    editUser: "Editar usuario",
    updateUserDesc: "Actualizar información y permisos del usuario",
    userInformation: "Información del usuario",
    userId: "ID de usuario",
    created: "Creado",
    lastLogin: "Último acceso",
    emailVerified: "Correo verificado",
    verified: "Verificado",
    notVerified: "No verificado",
    actionsLabel: "Acciones",
    unbanUser: "Desbanear usuario",
    banUser: "Banear usuario",
    awardCredits: "Otorgar créditos",
    profile: "Perfil",
    name: "Nombre",
    country: "País",
    timezone: "Zona horaria",
    editUserDetails: "Editar datos del usuario",
    changingRoleHint: "Cambiar el rol afectará los permisos y el acceso del usuario",
    bannedUsersHint: "Los usuarios baneados no pueden iniciar sesión",
    saving: "Guardando...",
    saveChanges: "Guardar cambios",
    cancel: "Cancelar",
    awardCreditsTitle: "Otorgar créditos",
    amountLabel: "Cantidad (1–1000)",
    reasonOptional: "Motivo (opcional)",
    reasonPlaceholder: "ej. Contribución al foro",
    sending: "Enviando...",
    award: "Otorgar",
    userUpdatedSuccess: "¡Usuario actualizado correctamente!",
    userBannedSuccess: "El usuario ha sido baneado.",
    userUnbannedSuccess: "El usuario ha sido desbaneado.",
    creditsAwardedSuccess: "Créditos otorgados. Nuevo saldo:",
    failedToBan: "Error al banear usuario",
    failedToUnban: "Error al desbanear usuario",
    failedToAwardCredits: "Error al otorgar créditos",

    bookingsManagement: "Gestión de reservas",
    viewManageBookings: "Ver y gestionar todas las reservas de clases",
    bookingId: "ID de reserva",
    studentColumn: "Estudiante",
    dateTime: "Fecha y hora",
    loadingBookings: "Cargando reservas...",
    noBookingsFound: "No se encontraron reservas",
    view: "Ver",
    cancelAction: "Cancelar",
    totalBookingsLabel: "Total de reservas",
    booked: "Reservado",
    completed: "Completado",
    totalCredits: "Total créditos",
    noShow: "No asistió",
    cancelled: "Cancelado",
    unknown: "Desconocido",

    teacherManagement: "Gestión de profesores",
    manageTeachersDesc: "Gestionar profesores y sus perfiles",
    loadingTeachers: "Cargando profesores...",
    noTeachersFound: "No se encontraron profesores",
    noNameSet: "Sin nombre",
    joinedDate: "Registrado",
    emailVerifiedLabel: "Correo verificado",
    viewProfile: "Ver perfil",
    moreActions: "Más acciones",
    editDetails: "Editar datos",
    suspendTeacher: "Suspender profesor",
    activateTeacher: "Activar profesor",
    banTeacher: "Banear profesor",
    totalTeachers: "Total de profesores",
    verifiedEmail: "Correo verificado",
    withProfile: "Con perfil",

    financeTitle: "Finanzas",
    financeDesc: "Ingresos, pagos y resumen financiero",
    failedToLoadFinance: "Error al cargar el resumen financiero",
    loadingFinanceData: "Cargando datos financieros…",
    estRevenueUsd: "Ingresos est. (USD)",
    fromCreditPurchases: "Por compras de créditos (precios de paquetes)",
    creditsPurchased: "Créditos comprados",
    transactionsCount: "transacción(es)",
    creditsSpent: "Créditos gastados",
    onCompletedCancelled: "En clases completadas/canceladas",
    creditsRefunded: "Créditos reembolsados",
    cancellations: "Cancelaciones",
    creditsPurchasedLast30: "Créditos comprados (últimos 30 días)",
    teacherEarningsCredits: "Ingresos de profesores (créditos)",
    creditsEarned: "Créditos ganados",
    completedClasses: "Clases completadas",
    noCompletedBookings: "Aún no hay reservas completadas.",
    recentCreditTransactions: "Transacciones de créditos recientes",
    date: "Fecha",
    type: "Tipo",
    amount: "Cantidad",
    method: "Método",
    userLabel: "Usuario",
    noTransactions30Days: "No hay transacciones en los últimos 30 días.",

    settingsTitle: "Configuración",
    settingsDesc: "Configuración del panel y la plataforma",
    settingsComingSoon: "Módulo de configuración próximamente",
    settingsComingSoonDesc: "Aquí podrás configurar opciones globales, funciones y preferencias de administración cuando la API de configuración esté disponible.",

    forumManagement: "Gestión del foro",
    forumModerateDesc: "Moderar artículos, adjuntos y acciones de usuarios",
    viewForum: "Ver foro",
    pendingArticles: "Artículos pendientes",
    pendingAttachments: "Adjuntos pendientes",
    userActions: "Acciones de usuario",
    loading: "Cargando...",
    noPendingArticles: "No hay artículos pendientes",
    review: "Revisar",
    approve: "Aprobar",
    rejectionReasonPlaceholder: "Motivo del rechazo...",
    reject: "Rechazar",
    noPendingAttachments: "No hay adjuntos pendientes",
    open: "Abrir",
    awardCreditsTitleForum: "Otorgar créditos",
    userIdLabel: "ID de usuario",
    userObjectIdPlaceholder: "ObjectId del usuario",
    amountLabelForum: "Cantidad",
    reasonOptionalForum: "Motivo (opcional)",
    reasonForAwarding: "Motivo para otorgar créditos",
    awardCreditsButton: "Otorgar créditos",
    banUserTitle: "Banear usuario",
    unbanUserTitle: "Desbanear usuario",
    provideRejectionReason: "Por favor indica un motivo de rechazo.",
    provideAttachmentRejectionReason: "Por favor indica un motivo de rechazo del adjunto.",
  },
};

export function translate(key: string, language: SupportedLanguage = "en"): string {
  const table = translations[language];
  return (table && table[key]) || key;
}
