export type SupportedLanguage = "en" | "es";

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Profile page
    profile: "Profile",
    editProfile: "Edit profile",
    loadingProfile: "Loading profile...",
    errorLoadingProfile: "Error loading profile",
    backToDashboard: "Back to dashboard",
    explorer: "Explorer",
    grade: "Grade",
    absoluteBeginner: "Absolute beginner",
    lessonsCompleted: "Lessons completed",
    feedbackGiven: "Feedback given",
    ratingFromTeachers: "Rating from teachers",
    yourMonedas: "Your Monedas",
    yourCredits: "Your Credits",
    buyCredits: "Buy credits",
    profileDetails: "Profile details",
    emailVerified: "Email verified",
    emailNotVerified: "Email not verified",
    learningObjectives: "Learning Objectives",
    spanishLevel: "Spanish Level",
    level: "Level",
    canRead: "Can read?",
    parentContactInfo: "Parent Contact Information",
    parentName: "Parent Name",
    telephoneNumber: "Telephone Number",
    additionalInfo: "Additional Information",
    nickname: "Nickname",
    birthdate: "Birthdate",
    homeschoolFunding: "Homeschool funding",
    home: "Home",

    // Profile modify page
    editProfileTitle: "Edit Profile",
    updateProfileInfo: "Update your profile information",
    saving: "Saving...",
    saveChanges: "Save Changes",
    profilePhoto: "Profile Photo",
    uploadPhoto: "Upload Photo",
    yourNickname: "Your nickname",
    selectLevel: "Select level...",
    beginner: "Beginner",
    elementary: "Elementary",
    intermediate: "Intermediate",
    upperIntermediate: "Upper Intermediate",
    advanced: "Advanced",
    nativeFluent: "Native/Fluent",
    select: "Select...",
    yes: "Yes",
    no: "No",
    learningObjectivesPlaceholder: "What are your learning goals?",
    parentGuardianName: "Parent/Guardian name",
    parentPhonePlaceholder: "+1...",
    cancel: "Cancel",
    loading: "Loading...",
  },
  es: {
    profile: "Perfil",
    editProfile: "Editar perfil",
    loadingProfile: "Cargando perfil...",
    errorLoadingProfile: "Error al cargar el perfil",
    backToDashboard: "Volver al panel",
    explorer: "Explorador",
    grade: "Calificación",
    absoluteBeginner: "Principiante absoluto",
    lessonsCompleted: "Clases completadas",
    feedbackGiven: "Comentarios dados",
    ratingFromTeachers: "Valoración de profesores",
    yourMonedas: "Tus Monedas",
    yourCredits: "Tus créditos",
    buyCredits: "Comprar créditos",
    profileDetails: "Detalles del perfil",
    emailVerified: "Correo verificado",
    emailNotVerified: "Correo no verificado",
    learningObjectives: "Objetivos de aprendizaje",
    spanishLevel: "Nivel de español",
    level: "Nivel",
    canRead: "¿Puede leer?",
    parentContactInfo: "Información de contacto del padre",
    parentName: "Nombre del padre",
    telephoneNumber: "Número de teléfono",
    additionalInfo: "Información adicional",
    nickname: "Apodo",
    birthdate: "Fecha de nacimiento",
    homeschoolFunding: "Financiación homeschool",
    home: "Inicio",

    editProfileTitle: "Editar perfil",
    updateProfileInfo: "Actualiza tu información de perfil",
    saving: "Guardando...",
    saveChanges: "Guardar cambios",
    profilePhoto: "Foto de perfil",
    uploadPhoto: "Subir foto",
    yourNickname: "Tu apodo",
    selectLevel: "Seleccionar nivel...",
    beginner: "Principiante",
    elementary: "Elemental",
    intermediate: "Intermedio",
    upperIntermediate: "Intermedio alto",
    advanced: "Avanzado",
    nativeFluent: "Nativo/Fluido",
    select: "Seleccionar...",
    yes: "Sí",
    no: "No",
    learningObjectivesPlaceholder: "¿Cuáles son tus objetivos de aprendizaje?",
    parentGuardianName: "Nombre del padre/tutor",
    parentPhonePlaceholder: "+1...",
    cancel: "Cancelar",
    loading: "Cargando...",
  },
};

/**
 * Translates a string key into the requested language.
 * Falls back to the original key when no translation is found.
 */
export function translate(key: string, language: SupportedLanguage = "en"): string {
  const table = translations[language];
  return (table && table[key]) || key;
}
